### ISSUE TITLE
Python 3.7

### ISSUE THREAD

**Issue by cdupont** [kirei/python-base45#10]
Hello,
just a question, is Python 3.7 absolutely necessary?

**Comment by jschlyter** [comment]
I'm not sure, please try and run the test cases with 3.6 and see what happens. Since Python 3.6 is soon EOL (december 2021) I have not done any testing at all with it. It would be easy to add though.

**Comment by jschlyter** [comment]
I've added 3.6 to the test cases and they pass just fine. Next release will be marked as ok for 3.6.
