### ISSUE TITLE
missing setup.py ?

### ISSUE THREAD

**Issue by Tolmino** [kirei/python-base45#11]
hi, i have tried to install using pip
and result
 ERROR: No matching distribution found

maybe for missing setup.py ?

**Comment by jschlyter** [comment]
Installation from source is via `poetry install`. If you are installing from pypi, you can simply use `pip3 install base45`.

**Comment by Tolmino** [comment]
Ok thanks ... now it works with pypi

some days ago i had that:
pip3 install base45 
ERROR: Could not find a version that satisfies the requirement base45 (from versions: none)
ERROR: No matching distribution found for base45

but today it is ok:
 pip3 install base45 
Collecting base45
  Downloading base45-0.4.3-py3-none-any.whl (3.5 kB)
Installing collected packages: base45
Successfully installed base45-0.4.3

Thanks again
