### ISSUE TITLE
"Could not find a version that satisfies the requirements base45" on Raspberry Pi 

### ISSUE THREAD

**Issue by lennertholvoet** [kirei/python-base45#13]
When installing base45 with `pip3 install base45` on RBPi - with Python v3.10.0 I get the "Could not find a version that staisfies tge requirement base45 (from versions: ) No Matching distribution found for base 45"

Is Python 3.10 or RBPi not supported?

**Comment by jschlyter** [comment]
I've just tried and `pip3 install base45` works fine on Python 3.10.0. Are you installing from pypi?

Unit tests are configured for Python 3.6 - 3.10.

**Comment by lennertholvoet** [comment]
Must have been a local error. Thank you for confirming.
Needed to reinstall RBPi OS because of errors, and now the installation of base45 worked without problems.
Probably did something wrong with my Python installation.
