### ISSUE TITLE
no version found

### ISSUE THREAD

**Issue by alexxxmg** [kirei/python-base45#5]
hi!
I tried installing **base45** by `pip install base45` (or `pip3 install base45`), but I got this:

```
ERROR: Could not find a version that satisfies the requirement base45 (from versions: none)
ERROR: No matching distribution found for base45
```

any hint?

Alessandro

**Comment by jschlyter** [comment]
What version of Python do you have? Python 3.7 or later is required for `base45`.

**Comment by alexxxmg** [comment]
On 6/29/21 4:30 PM, Jakob Schlyter
      wrote:
    
    
      
      What version of Python do you have?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/kirei/python-base45/issues/5#issuecomment-870652320",
"url": "https://github.com/kirei/python-base45/issues/5#issuecomment-870652320",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    Hi, thank you for your help!
    
    
    # python -V
      Python 2.7.15
      # python3 -V
      Python 3.6.6
      
    
    -- 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/  Dr.Alessandro Magni
\        Materials and Life Sciences
/        INRiM Strada delle Cacce 91, 10135 Torino (ITALIA)
\        Email ***@***.***
/        Tel +39 011 3919821  Fax +39 011 3919834
\ Our business in life is not to succeed but to continue to fail 
/ in high spirits.  -- Robert Louis Stevenson
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by jschlyter** [comment]
Only Python 3.7 and later is supported (see https://pypi.org/project/base45/)
